/*
 * generated by Xtext 2.17.0
 */
package mestra


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DmxLightShowStandaloneSetup extends DmxLightShowStandaloneSetupGenerated {

	def static void doSetup() {
		new DmxLightShowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
